# Generated by Django 5.2.4 on 2025-07-28 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the team member', max_length=100, verbose_name='Team Member Role')),
                ('role', models.CharField(help_text='Enter the role of the team member', max_length=50, verbose_name='Team Member Name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='team/')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date of Team Member')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date of Team Member')),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'db_table': 'team',
                'ordering': ['id'],
            },
        ),
    ]
