# Generated by Django 5.2.4 on 2025-07-28 15:59

import api.fields.CustomCloudinaryField
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='image',
            field=api.fields.CustomCloudinaryField(blank=True, default='team/default.jpg', folder_name='team', max_length=255, null=True),
        ),
    ]
