# Generated by Django 5.2.4 on 2025-07-30 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('staff', 'Staff'), ('admin', 'Admin')], default='staff', help_text='Select user role', verbose_name='Role of user'),
        ),
    ]
