# Generated by Django 5.2.4 on 2025-07-30 08:37

import cloudinary_storage.storage
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_team_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(help_text='Enter the name of the category', max_length=100, verbose_name='Category Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date of Category')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date of Category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'category',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Please upload the image', storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='product/', verbose_name='The image field for products')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date of Images')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date of Images')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'db_table': 'image',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Automatically generated unique ID for the order', unique=True, verbose_name='Order Unique ID')),
                ('order_duedate', models.DateTimeField(help_text='Enter due date for Order', verbose_name='Order Due Date')),
                ('order_total_price', models.DecimalField(decimal_places=2, help_text='Enter the total price of the order', max_digits=10, verbose_name='Order Total Price')),
                ('order_status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in process', 'In Process'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='pending', help_text='Current status of the order', max_length=10, verbose_name='Order Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date of Reviews')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date of Reviews')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': 'order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(help_text='Enter the quantity', verbose_name='Enter the quantity of product in the order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date of Reviews')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date of Reviews')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.order')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
                'db_table': 'orderitem',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(help_text='Enter the name of product', max_length=100, verbose_name='Product name')),
                ('product_price', models.DecimalField(decimal_places=2, help_text='Enter the price of product', max_digits=10, verbose_name='Product price')),
                ('product_like_count', models.PositiveIntegerField(default=0, help_text='Enter the like count of product', verbose_name='Product like count')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'product',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(help_text='Enter the name of the customer', max_length=100, verbose_name='Customer name')),
                ('customer_email', models.EmailField(help_text='Enter the email of the customer', max_length=100, verbose_name='Customer email')),
                ('customer_phone', models.CharField(help_text='Enter the phone number of the customer', max_length=100, verbose_name='Customer phone number')),
                ('reservation_date', models.DateTimeField(help_text='Select the date and time of reservation', verbose_name='Reservation Date')),
                ('customer_message', models.CharField(help_text='Enter the message of the customer', max_length=2000, verbose_name='Customer message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date of Reservation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date of Reservation')),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
                'db_table': 'reservation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(help_text='Enter the name of the reviewer', max_length=100, verbose_name='Reviewer email')),
                ('reviewer_email', models.EmailField(help_text='Enter the email of the reviewer', max_length=100, verbose_name='Reviewer email')),
                ('reviewer_comment', models.TextField(help_text='Enter the comment of the reviewer', verbose_name='Reviewer comment')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date of Reviews')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date of Reviews')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.product')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'db_table': 'review',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Teammate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teammate_name', models.CharField(help_text='Enter the name of the team member', max_length=100, verbose_name='Team Member Name')),
                ('teammate_role', models.CharField(help_text='Enter the role of the team member', max_length=50, verbose_name='Team Member Role')),
                ('teammate_image', models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='team/')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date of Team Member')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date of Team Member')),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'db_table': 'teammate',
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='api.product'),
        ),
        migrations.AddField(
            model_name='images',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.product'),
        ),
    ]
