# Generated by Django 5.2.4 on 2025-08-01 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_product_created_at_product_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(default='product/cake.jpg', help_text='Upload the thumbnail image of product', upload_to='products/', verbose_name='Product thumbnail'),
            preserve_default=False,
        ),
    ]
