# Generated by Django 5.2.4 on 2025-08-05 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_product_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_description',
            field=models.TextField(blank=True, help_text='Enter the description of product', verbose_name='Product description'),
        ),
    ]
