# Generated by Django 5.2.4 on 2025-08-05 20:46

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_product_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(help_text='Upload the thumbnail image of product', storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='products/', verbose_name='Product thumbnail'),
        ),
    ]
