# Generated by Django 5.2.4 on 2025-08-20 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_product_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='number_of_people',
            field=models.PositiveIntegerField(default=1, help_text='Enter the number of people for the reservation', verbose_name='Number of People'),
        ),
    ]
