# version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    command: uv run gunicorn coffee_api.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./backend:/app
      - /app/.venv
    ports:
      - "8000:8000"
    environment:
      DJANGO_SETTINGS_MODULE: coffee_api.settings
      PYTHONUNBUFFERED: 1
    env_file:
      - ./backend/.env
  
  frontend:
    build:
      context: ./frontend/coffee_shop
      dockerfile: Dockerfile
    container_name: frontend
    volumes:
      - ./frontend/coffee_shop:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend