# Production Docker Compose Override
# Usage: docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d

services:
  backend:
    restart: unless-stopped
    environment:
      - DJANGO_DEBUG=False
    deploy:
      resources:
        limits:
          memory: 1g
          cpus: '0.8'
        reservations:
          memory: 512m
          cpus: '0.4'

  frontend:
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512m
          cpus: '0.5'
        reservations:
          memory: 256m
          cpus: '0.25'

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

  db:
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 1g
          cpus: '0.8'
        reservations:
          memory: 512m
          cpus: '0.4'

  redis:
    restart: unless-stopped
    volumes:
      - redis_data:/data
    deploy:
      resources:
        limits:
          memory: 512m
          cpus: '0.5'
        reservations:
          memory: 256m
          cpus: '0.25'

  elasticsearch:
    restart: unless-stopped
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    deploy:
      resources:
        limits:
          memory: 2g
          cpus: '1.0'
        reservations:
          memory: 1g
          cpus: '0.5'

  mongo:
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    deploy:
      resources:
        limits:
          memory: 1g
          cpus: '0.8'
        reservations:
          memory: 512m
          cpus: '0.4'

  graylog:
    restart: unless-stopped
    volumes:
      - graylog_data:/usr/share/graylog/data
    deploy:
      resources:
        limits:
          memory: 1g
          cpus: '0.8'
        reservations:
          memory: 512m
          cpus: '0.4'

  celery:
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512m
          cpus: '0.5'
        reservations:
          memory: 256m
          cpus: '0.25'

  celery-beat:
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256m
          cpus: '0.3'
        reservations:
          memory: 128m
          cpus: '0.15'

  flower:
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256m
          cpus: '0.3'
        reservations:
          memory: 128m
          cpus: '0.15'

volumes:
  postgres_data:
  redis_data:
  elasticsearch_data:
  mongo_data:
  graylog_data:
