# version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    command: uv run gunicorn coffee_api.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./backend:/app
      - /app/.venv
    ports:
      - "8000:8000"
    environment:
      DJANGO_SETTINGS_MODULE: coffee_api.settings
      PYTHONUNBUFFERED: 1
    restart: always
    env_file:
      - ./backend/.env
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  frontend:
    build:
      context: ./frontend/coffee_shop
      dockerfile: Dockerfile
    container_name: frontend
    volumes:
      - ./frontend/coffee_shop:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mysql_data: 